#pragma once

#define ICON_MIN_OP 0xe000
#define ICON_MAX_OP 0xeea89e

#define OP_ICON "\xee\xa4\xa5"

#define OP_ICON_STAR_FILLED_1 "\xee\xa4\x8e"
#define OP_ICON_STAR_BORDER_1 "\xee\xa4\x8f"
#define OP_ICON_REDO "\xee\xa4\x90"
#define OP_ICON_UNDO "\xee\xa4\x91"
#define OP_ICON_REMOVE "\xee\xa4\x92"
#define OP_ICON_ADD "\xee\xa4\x93"
#define OP_ICON_MEASURE "\xee\xa4\x94"
#define OP_ICON_CLEAR "\xee\xa4\x95"
#define OP_ICON_INVENTORY "\xee\xa4\x96"
#define OP_ICON_TRANSFORM_2 "\xee\xa4\x97"
#define OP_ICON_ZOOM "\xee\xa4\x98"
#define OP_ICON_BUILD "\xee\xa4\x9a"
#define OP_ICON_FAVORITE_BORDER "\xee\xa4\x9b"
#define OP_ICON_FAVORITE_FILLED "\xee\xa4\x9c"
#define OP_ICON_SEARCH "\xee\xa4\x9d"
#define OP_ICON_ERROR_1 "\xee\xa4\x9e"
#define OP_ICON_WARNING_1 "\xee\xa4\x9f"
#define OP_ICON_VISIBILITY_ON "\xee\xa4\xa0"
#define OP_ICON_VISIBILITY_OFF "\xee\xa4\xa1"

#define OP_ICON_LIGHT "\xee\xa4\x80"
#define OP_ICON_CAMERA "\xee\xa4\x81"
#define OP_ICON_PHYSICS "\xee\xa4\x82"
#define OP_ICON_TRANSFORM "\xee\xa4\x83"
#define OP_ICON_WARNING "\xee\xa4\x84"
#define OP_ICON_SUCCESS "\xee\xa4\x85"
#define OP_ICON_STAR_OUTLINED "\xee\xa4\x86"
#define OP_ICON_STAR_FILLED "\xee\xa4\x87"
#define OP_ICON_PLAY "\xee\xa4\x88"
#define OP_ICON_PAUSE "\xee\xa4\x89"
#define OP_ICON_COLLECTION "\xee\xa4\x8a"
#define OP_ICON_WAV "\xee\xa4\x8b"
#define OP_ICON_JPG "\xee\xa4\x8c"
#define OP_ICON_HEART_OUTLINED "\xee\xa4\x8d"


#define OP_ICON_FILE_EMPTY "\xee\xa4\xa4"
#define OP_ICON_STACK "\xee\xa4\xae"
#define OP_ICON_FOLDER "\xee\xa4\xaf"
#define OP_ICON_FOLDER_OPEN "\xee\xa4\xb0"
#define OP_ICON_EQUALIZER "\xee\xa6\x92"
#define OP_ICON_BUG "\xee\xa6\x99"
#define OP_ICON_BIN "\xee\xa6\xad"
#define OP_ICON_FLAG "\xee\xa7\x8c"
#define OP_ICON_EYE "\xee\xa7\x8e"
#define OP_ICON_EYE_BLOCKED "\xee\xa7\x91"
#define OP_ICON_PLUS "\xee\xa8\x8a"
#define OP_ICON_MINUS "\xee\xa8\x8b"
#define OP_ICON_PLAY_2 "\xee\xa8\x9c"
#define OP_ICON_PAUSE_2 "\xee\xa8\x9d"
#define OP_ICON_STOP "\xee\xa8\x9e"